// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEcyJZFAR8YVPyQn02R9rJP-fFH38_tQ',
    appId: '1:206852320406:web:1e3577f5498c68069326b7',
    messagingSenderId: '206852320406',
    projectId: 'recipefinder-7f50a',
    authDomain: 'recipefinder-7f50a.firebaseapp.com',
    storageBucket: 'recipefinder-7f50a.appspot.com',
    measurementId: 'G-1F5VZY10V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXpUENGHgtM40l2zc3ZMwZjA0giURTaWM',
    appId: '1:206852320406:android:8e860584d78c63839326b7',
    messagingSenderId: '206852320406',
    projectId: 'recipefinder-7f50a',
    storageBucket: 'recipefinder-7f50a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM7F2byWavGsl9e3cGDmenmAcoE-zyMdI',
    appId: '1:206852320406:ios:5fcb0d6a771405409326b7',
    messagingSenderId: '206852320406',
    projectId: 'recipefinder-7f50a',
    storageBucket: 'recipefinder-7f50a.appspot.com',
    iosClientId: '206852320406-mu41ri525vnodqnpk9s34hk5p9o6tudk.apps.googleusercontent.com',
    iosBundleId: 'com.recipe.app',
  );
}
